import pygame
import os
# importing all required files
pygame.mixer.init()
EARTH_SHIP = pygame.image.load(os.path.join("images", "earth.png"))
WATER_SHIP = pygame.image.load(os.path.join("images", "water.png"))
FIRE_SHIP = pygame.image.load(os.path.join("images", "fire.png"))
AIR_SHIP = pygame.image.load(os.path.join("images", "air.png"))
WATER_BULLET = pygame.image.load(os.path.join("images", "waterBullet.png"))
EARTH_BULLET = pygame.image.load(os.path.join("images", "earthBullet.png"))
AIR_BULLET = pygame.image.load(os.path.join("images", "airBullet.png"))
FIRE_BULLET = pygame.image.load(os.path.join("images", "fireBullet.png"))
ENEMY_SHIP1 = pygame.image.load(os.path.join("images", "enemy1.png"))
ENEMY_BULLET1 = pygame.image.load(os.path.join("images", "enemyBullet1.png"))
ENEMY_SHIP2 = pygame.image.load(os.path.join("images", "enemy2.png"))
ENEMY_BULLET2 = pygame.image.load(os.path.join("images", "enemyBullet2.png"))
ENEMY_SHIP3 = pygame.image.load(os.path.join("images", "enemy3.png"))
ENEMY_BULLET3 = pygame.image.load(os.path.join("images", "enemyBullet3.png"))
ENEMY_SHIP4 = pygame.image.load(os.path.join("images", "enemy4.png"))
EARTH_MISSILE = pygame.image.load(os.path.join("images", "earthMissile.png"))
WATER_MISSILE = pygame.image.load(os.path.join("images", "waterMissile.png"))
FIRE_MISSILE = pygame.image.load(os.path.join("images", "fireMissile.png"))
AIR_MISSILE = pygame.image.load(os.path.join("images", "airMissile.png"))
ENEMY_BULLET4 = pygame.image.load(os.path.join("images", "enemyBullet4.png"))
BOSS_SHIP = pygame.image.load(os.path.join("images", "boss.png"))
BOSS_BULLET = pygame.image.load(os.path.join("images", "bossBullet.png"))
BACKGROUND = pygame.image.load(os.path.join("images", "dve2Pj.jpg"))
SETTINGS_BG = pygame.image.load(os.path.join("images", "settingsBG.jpg"))
SELECTION_SCREEN_BG = pygame.image.load(os.path.join("images", "selection_screen.png"))
INSTRUCTIONS_BG = pygame.image.load(os.path.join("images", "instruct-image.jpg"))
HIGH_BG = pygame.image.load(os.path.join("images", "high-score.jpg"))
LOST_BG = pygame.image.load(os.path.join("images", "lost_message.png"))
CREDITS_BG = pygame.image.load(os.path.join("images", "credits.jpg"))
MENU_TRACK = pygame.mixer.Sound(os.path.join("soundtracks", "menu.wav"))
LEVEL_TRACK = pygame.mixer.Sound(os.path.join("soundtracks", "Levels.ogg"))
LOSE_TRACK = pygame.mixer.Sound(os.path.join("soundtracks", "You-lose.mp3"))
FINALE_TRACK = pygame.mixer.Sound(os.path.join("soundtracks", "finale.mp3"))
FIRE = pygame.mixer.Sound(os.path.join("soundtracks", "bullet_fire.mp3"))
MISSILE = pygame.mixer.Sound(os.path.join("soundtracks", "missile.mp3"))
